import random

settings = {
    "players": [
        {
            "name": "Yellow",
            "color": "yellow",
            "beginner": False,
            "handicap": 0,
            "first": False
        },
        {
            "name": "Red",
            "color": "red",
            "beginner": False,
            "handicap": 0,
            "first": False
        },
        {
            "name": "Green",
            "color": "green",
            "beginner": False,
            "handicap": 0,
            "first": False
        }
    ],
    "corporateEra": True,
    "prelude": True,
    "prelude2Expansion": False,
    "draftVariant": True,
    "showOtherPlayersVP": False,
    "venusNext": False,
    "colonies": False,
    "turmoil": False,
    "customCorporationsList": [],
    "customColoniesList": [],
    "customPreludes": [],
    "bannedCards": [],
    "includedCards": [],
    "board": "tharsis",
    "seed": random.random(),
    "solarPhaseOption": False,
    "promoCardsOption": False,
    "communityCardsOption": False,
    "aresExtension": False,
    "politicalAgendasExtension": "Standard",
    "moonExpansion": False,
    "pathfindersExpansion": False,
    "undoOption": False,
    "showTimers": True,
    "fastModeOption": False,
    "removeNegativeGlobalEventsOption": False,
    "includeVenusMA": True,
    "includeFanMA": False,
    "modularMA": False,
    "startingCorporations": 2,
    "soloTR": False,
    "initialDraft": False,
    "preludeDraftVariant": True,
    "randomMA": "No randomization",
    "shuffleMapOption": False,
    "randomFirstPlayer": True,
    "requiresVenusTrackCompletion": False,
    "requiresMoonTrackCompletion": False,
    "moonStandardProjectVariant": False,
    "moonStandardProjectVariant1": False,
    "altVenusBoard": False,
    "escapeVelocityMode": False,
    "escapeVelocityBonusSeconds": 2,
    "twoCorpsVariant": False,
    "ceoExtension": False,
    "customCeos": [],
    "startingCeos": 3,
    "startingPreludes": 4,
    "starWarsExpansion": False,
    "underworldExpansion": False
}
